keys:
  # Users
  - &daniel age1wfcrg7q0tdpur78ru9yek4r4k4tdhmrf5gk8zxgp783pq3pq6pwstxuu7f
  # Hosts
  - &zorg age1fewd275jjkjpz5w843jtnxqujtr0vd3qrxt9lv4sdk3auzes4ezqkemuql
  - &tars age10qza7vm0ykd50c7efp7nm68jwq2feg5dwzs48hs7ml86cex7cuwq07un2q
  - &hal age1m8pjnmrge8yhsxds2s0khrnvp9w0ejsjr0uzt4wsyhz70vtk9pxqxmauyg
  - &jarvis age153kxcgxzk2n7pkyrr75mr7h0yksfgyw8e6y508eq3c0xgu2eqslsjuq6pn
  - &skynet age1rm5jkrd4qa5c35sem9mzq2vq7etz25sn0g8w6wjfvkg4uuq0jccq0e5tzh

creation_rules:
  - path_regex: modules/nixos/secrets.ya?ml$
    key_groups:
      - age:
          - *daniel
          - *zorg
          - *tars
          - *hal
          - *jarvis
          - *skynet

  - path_regex: modules/nixos/services/secrets.ya?ml$
    key_groups:
      - age:
          - *daniel
          - *zorg
          - *tars
          - *hal
          - *jarvis
          - *skynet

  - path_regex: modules/home/secrets.ya?ml$
    key_groups:
      - age:
          - *daniel
          - *zorg
          - *tars
          - *hal
          - *jarvis
          - *skynet
