# Minimal hardware config for Hetzner CX42 (KVM guest).
# Will be regenerated by nixos-anywhere during install.
{
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "virtio_pci"
      "virtio_scsi"
      "ahci"
      "sd_mod"
    ];
    kernelParams = [ "console=tty" ];
  };

  swapDevices = [ ];

  networking = {
    useDHCP = lib.mkDefault true;
    hostName = "jarvis";
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
